<div class="modal fade js-table-edit" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <form method="POST" action="" target="submitter">
      <div class="modal-body">
         
              <?php foreach ($fields as $field) {
                        echo $store->fetchParser($field['type'], $field);
                    }
              ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <input type="hidden" name="action" value="save">
        <button type="submit" class="btn btn-primary js-save-item" data-id="<?php echo $id;?>">Save changes</button>
      </div>
      </form>
      <iframe class="hidden" id="submitter" name="submitter"></iframe>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->